[project]
name = 'Carbonix'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Carbonix]
path = 'contracts/Carbonix.clar'
clarity_version = 3
epoch = 3.1
[contracts.carbon-impact-analytics]
path = 'contracts/carbon-impact-analytics.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
